---
- name: package test
  hosts: ubuntuvm
  become: true
  vars:
    cowsay_package_name: cowsay

  tasks:
  - name: install cowsay
    ansible.builtin.package:
      name: "{{ cowsay_package_name}}"
      state: present


